<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'dev',
  'APP_SECRET' => '1ccd8b7aa5b5d698a39a4ae06196f8a9',
  'DATABASE_URL' => 'pgsql://postgres:@127.0.0.1:5432/insta',
  'MAILER_URL' => 'null://localhost',
);
